services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate-api-express
    image: boilerplate-api-express:latest
    ports:
      - 3000:3000
    env_file:
      - .env